name = "uglink-worker"
main = "dist/index.js"
compatibility_date = "2025-04-09"
compatibility_flags = ["nodejs_compat"]
[vars]
BASE_URL = "192-168-31-41.hmau.direct.ug.link"
PORT = "9443"
USERNAME = "hmau"

[[kv_namespaces]]
binding = "UGLINK_CACHE"
id = ""  # Replace with your actual KV namespace ID from Cloudflare dashboard

[observability.logs]
enabled = true
